version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: "rabbitmq"

  worker:
    build: .
    command: celery -A celery_app worker --loglevel=info
    environment:
      - CELERY_BROKER=amqp://guest:guest@rabbitmq:5672//
      - CELERY_BACKEND=rpc://
      - SQLALCHEMY_DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - YOUR_EMAIL=${YOUR_EMAIL}
      - YOUR_PASSWORD=${YOUR_PASSWORD}
    depends_on:
      - rabbitmq
      - db

  web:
    build: .
    ports:
      - "8000:80"
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    depends_on:
      - db
      - rabbitmq

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST_AUTH_METHOD=trust

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m  # Limita o heap do Java para o Elasticsearch
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.0
    ports:
      - "5000:5000"
    volumes:
      - ./logstash:/usr/share/logstash/pipeline
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus  # Presume-se que você tenha um diretório prometheus com prometheus.yml nele
    ports:
      - "9090:9090"
    depends_on:
      - web  # Dependendo do seu serviço web para coletar métricas
      - node-exporter  # Dependendo do node-exporter para coletar métricas do sistema

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin  # Você pode definir um usuário administrador
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Substitua 'admin' pela senha que você deseja para o administrador
    volumes:
      - grafana_data:/var/lib/grafana  # Persistência de dados do Grafana

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"

volumes:
  postgres_data:
  elasticsearch_data:
    driver: local
  grafana_data:  # Adicionado para persistência de dados do Grafana
    driver: local
  prometheus_data:  # Adicionado para persistência de dados do Prometheus
    driver: local

